### ISSUE TITLE
Life Support Error

### ISSUE THREAD

**Issue by TheSuperPlayer** [ludsoe/Environments-X#3]
Since the new update when i am turning on LS i keep getting this error.

[ERROR] addons/environments-x-master/lua/entities/env_lscore/init.lua:172: attempt to index field 'environment' (a nil value)
  1. Regulate - addons/environments-x-master/lua/entities/env_lscore/init.lua:172
   2. OldThink - addons/environments-x-master/lua/entities/env_lscore/init.lua:353
    3. unknown - addons/environments-x-master/lua/lde/lde_core.lua:323

**Comment by ludsoe** [comment]
LS core now defaults to space environment when it fails its internal check.
