### ISSUE TITLE
Mining asteroid

### ISSUE THREAD

**Issue by Arwwarr** [ludsoe/Environments-X#5]
in mining asteroid is ... 

[ERROR] addons/environmentsx/lua/effects/eff_laserhit/init.lua:63: bad argument #1 to 'SetModelScale' (number expected, got userdata)
  1. SetModelScale - [C]:-1
   2. unknown - addons/environmentsx/lua/effects/eff_laserhit/init.lua:63

**Comment by ludsoe** [comment]
Fixed next update.
